### ISSUE TITLE
回答不了图片

### ISSUE THREAD

**Issue by Accelerator23333** [azmiao/XQA#17]
回答图片时失败，回答文字正常使用
[2024-09-24 18:01:09,720 hoshino] CRITICAL: XQA: 调用get_image接口查询图片5b919f49ed1f226a59e4f1de77dcad17279090-999-1377.png出错:<ActionFailed status='failed', retcode=-1, msg='Value of "this" must be of type URLSearchParams', wording='ws-plugin获取信息失败', echo={'seq': 2}>
[2024-09-24 18:01:09,720] CRITICAL in util: XQA: 调用get_image接口查询图片5b919f49ed1f226a59e4f1de77dcad17279090-999-1377.png出错:<ActionFailed status='failed', retcode=-1, msg='Value of "this" must be of type URLSearchParams', wording='ws-plugin获取信息失败', echo={'seq': 2}>
[2024-09-24 18:01:09,721 XQA] ERROR: <class 'TypeError'> occured when set_question handling message -1820556216.
[2024-09-24 18:01:09,721] ERROR in service: <class 'TypeError'> occured when set_question handling message -1820556216.
[2024-09-24 18:01:09,722 XQA] ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\__init__.py", line 115, in set_question
    msg = await set_que(bot, group_id, user_id, que_raw, ans_raw, str(ev.group_id))
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\operate_msg.py", line 20, in set_que
    ans_raw = await adjust_img(bot, ans_raw, save=True)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\util.py", line 162, in adjust_img
    raw_body = await doing_img(bot, raw_body, is_ans, save)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\util.py", line 139, in doing_img
    url = img_data['url']
TypeError: 'NoneType' object is not subscriptable
[2024-09-24 18:01:09,722] ERROR in service: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\__init__.py", line 115, in set_question
    msg = await set_que(bot, group_id, user_id, que_raw, ans_raw, str(ev.group_id))
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\operate_msg.py", line 20, in set_que
    ans_raw = await adjust_img(bot, ans_raw, save=True)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\util.py", line 162, in adjust_img
    raw_body = await doing_img(bot, raw_body, is_ans, save)
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\XQA\util.py", line 139, in doing_img
    url = img_data['url']
TypeError: 'NoneType' object is not subscriptable

**Comment by azmiao** [comment]
请提供BOT实现客户端和对应版本，这边推荐使用gocqhttp1.2.0

**Comment by Accelerator23333** [comment]
用ws插件连接的云崽机器人
https://gitee.com/xiaoye12123/ws-plugin

**Comment by azmiao** [comment]
> 用ws插件连接的云崽机器人 https://gitee.com/xiaoye12123/ws-plugin

请看该项目文档下方实现API，未适配get_image接口，因此无法实现本功能，建议等待其实现后再尝试哦
